### ISSUE TITLE
Auth Token - documentation

### ISSUE THREAD

**Issue by DanyHubGit** [g3w-suite/g3w-suite-documentation#14]
Hi All,
I would have some information about the use of the Auth Token section (found in Django Administration).
I have read the documentation, but I haven't found nothing that can help me.

I would know how the Auth Token, associated to a specific user, can be used by external script or by external application.
Can you suggest any guide or reference to use these tokens? Do auth tokens needs NGIX to be configured in some specific manner?

Thanks for all information provided.

**Comment by Raruto** [comment]
This is not an answer, I'm just attaching a few self-explanatory images below to show others what we are talking about:

## Django Admin > Auth Token

http://localhost:8000/en/django-admin/

![image](https://user-images.githubusercontent.com/9614886/220375669-44756f50-45b2-47b2-8dc6-9f230af39306.png)

## Django Admin > Auth Token > Tokens

http://localhost:8000/en/django-admin/authtoken/token/

![image](https://user-images.githubusercontent.com/9614886/220376047-90765149-6db9-4fba-b02b-0b40ef2bc37b.png)

**Comment by Raruto** [comment]
>  I would have some information about the use of the Auth Token section (found in Django Administration).
> I have read the documentation, but I haven't found nothing that can help me.
> 
> I would know how the Auth Token, associated to a specific user, can be used by external script or by external application.
> Can you suggest any guide or reference to use these tokens? Do auth tokens needs NGIX to be configured in some specific manner?

@DanyHubGit from a quick look to the following line I have the suspect that settings are related to the [Django Rest Framework](https://www.django-rest-framework.org/):

## • [g3w-admin/base/settings/base.py#L55](https://github.com/g3w-suite/g3w-admin/blob/261c1fe7529bde437524b58e184a97e9c73a7db1/g3w-admin/base/settings/base.py#L55)

```py
THIRD_PARTY_APPS = [
  ...
  
  'rest_framework.authtoken',
  
  ...
]
```

**For more info:**

- [Django Rest Framework > API Guide > Token Authentication](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication)
- [How to implement token authentication using django rest framework](https://simpleisbetterthancomplex.com/tutorial/2018/11/22/how-to-implement-token-authentication-using-django-rest-framework.html)

👋 Raruto
