### ISSUE TITLE
Adding a custom basemap provider

### ISSUE THREAD

**Issue by adrriandiaconu** [g3w-suite/g3w-suite-documentation#32]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Hi,

I am trying to add Google maps Hybrid as a basemap.

I tried the following:
1. added to the env file:
![image](https://github.com/g3w-suite/g3w-admin/assets/49444442/5d4fd9f2-36ac-4a91-90de-f04176f82205)
2. added to docker-compose.yml 
![image](https://github.com/g3w-suite/g3w-admin/assets/49444442/aaa47a3c-aab2-480b-a6ee-db37f36a38cc)
I then restarted all the containers but I do not see the new basemap.

Can you please point me to the documentation where I can find out what else do I need to configure in order to add the new map.

Thank you in advance.

Regards,
Adrian

### Steps to reproduce

1. added to the env file:
![image](https://github.com/g3w-suite/g3w-admin/assets/49444442/5d4fd9f2-36ac-4a91-90de-f04176f82205)
2. added to docker-compose.yml 
![image](https://github.com/g3w-suite/g3w-admin/assets/49444442/aaa47a3c-aab2-480b-a6ee-db37f36a38cc)
I then restarted all the containers but I do not see the new basemap.

### Environment

g3w-suite:v3.6.x
g3w-suite:v3.6.x
any
ubuntu 22.04 docker install

**Comment by Raruto** [comment]
> Can you please point me to the documentation where I can find out what else do I need to configure in order to add the new map.

@adrriandiaconu I don't think it's explained anywhere in detail.

Once you add the [`VENDOR_KEYS`](https://g3w-suite.readthedocs.io/en/v3.7.x/settings.html#vendors-settings) I don't think there's much else to do.

>  I then restarted all the containers but I do not see the new basemap.

Where exactly did you look did you look for that?

If I'm not mistaken it should be found on the group management page (ie. not within single project settings)

![image](https://github.com/g3w-suite/g3w-suite-documentation/assets/9614886/48c8111e-e7c2-46c5-b30d-5a3f8701025f)

👋 Raruto

**Comment by adrriandiaconu** [comment]
> If I'm not mistaken it should be found on the group management page (ie. not within single project settings)

@Raruto yes that is the place where I looked for google basemap but it does not appear

**Comment by Raruto** [comment]
@adrriandiaconu ref: https://github.com/g3w-suite/g3w-suite-documentation/issues/32#issue-2148439514 I don't think it's necessary to edit your `docker-compose.yml`

Probably, once you have set your custom `VENDOR_KEYS` within the `.env` file you also need to add a new entry within **django-admin** to get listed within your groups/projects settings:

![image](https://github.com/g3w-suite/g3w-suite-documentation/assets/9614886/5adb8f7d-caac-457e-ae3d-55710f2a7475)

![image](https://github.com/g3w-suite/g3w-suite-documentation/assets/9614886/9261e8b5-af51-4c24-a98d-a423c7a6526a)

👋 Raruto

**Comment by adrriandiaconu** [comment]
@Raruto what do I need to add to the property field

![image](https://github.com/g3w-suite/g3w-suite-documentation/assets/49444442/dd1a87b4-950a-4516-9285-4c6b052d4a58)

**Comment by wlorenzetti** [comment]
Hi @adrriandiaconu, this is an example for google street:
```
{
"crs": {
      "epsg":3857,
      "proj4":"+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs",
      "geographic":False,
      "axisinverted":False
   },
"url": "https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}" ,
"servertype": "TMS",
"attributions": "Google"
}
```
But Attention, after last restricted terms of google license I think is not possible show data on base google maps without the use of GMap SDK.

**Comment by adrriandiaconu** [comment]
![image](https://github.com/g3w-suite/g3w-suite-documentation/assets/49444442/7bb67f14-ad63-4063-8e7e-d2776b583721)
thank you I have found some property and it seems to work

**Comment by adrriandiaconu** [comment]
thnak you very much for all your help!

**Comment by Raruto** [comment]
> thank you very much for all your help!

@adrriandiaconu whether possible please try creating a [PR](https://github.com/g3w-suite/g3w-suite-documentation/pulls) by inserting any missing steps.

It would help us a lot to have more external contributions regarding documentation.

👋 Raruto
