### ISSUE TITLE
Missing `G3WSUITE_CUSTOM_JS` explanation

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-suite-documentation#7]
Into https://g3w-suite.readthedocs.io/en/latest/settings.html is missing explanation about `G3WSUITE_CUSTOM_JS`.

**Comment by Raruto** [comment]
@wlorenzetti it has been addressed in **v3.5.x**? https://g3w-suite.readthedocs.io/en/v3.5.x/settings.html#g3wsuite-custom-js (or did you mean to add more information?)
